import type { Protocol } from '@/lib/protocol'

export const movementBattery: Protocol = {
  id: 'movement-battery-v1',
  name: 'Whole-body movement battery',
  summary:
    'A single suited session covering gait, change of direction, squat and hinge, reach, transitions, jumping, balance, loaded carries and falls.',
  rationale:
    'Establishes a per-subject baseline of whole-body kinematics before they are recorded doing anything useful. Everything else we capture is a person doing a job; this is the same person doing known movements, so drift, fit and subject-to-subject variation can be separated from task variation later.',
  duration: '45 to 60 minutes including calibration and rest',
  equipment: [
    'Suit and charged sensors',
    'Taped 10 m line and lane markings',
    '20 cm box, 30 cm box, 45 cm bench',
    '5 kg and 8 kg loads, medicine ball, resistance band',
    'Sled and strap, battle rope, fixed ladder, pull-up bar',
    'Whistle for cued trials',
  ],
  caveat:
    'This is the most saturated area of public human-motion data. AMASS, Human3.6M, 3DPW and the whole mocap industry cover gait, squats, lunges and balance thoroughly. Run this for calibration and subject baselining, not because the movements themselves are an under-covered gap. The genuinely scarce items in here are the loaded asymmetric carries, the externally cued reaction, and the deliberate bad-pattern contrast trial.',
  blocks: [
    {
      id: 'setup',
      title: 'Suit on and calibration',
      purpose: 'Get the sensors on the landmarks and give capture a known reference pose.',
      steps: [
        {
          text: 'Put the suit on so every sensor pocket sits on its landmark, then close the zip.',
          cue: 'Every pocket is on its landmark and the torso panel is not twisted.',
        },
        {
          text: 'Hold a T-pose: arms level with the shoulders, palms down, feet under the hips.',
          cue: 'Held still until capture reports it has settled.',
          restart: 'Any arm drop or weight shift before capture confirms.',
        },
        {
          text: 'Hold an A-pose: arms off the body, elbows soft.',
          cue: 'Arms come down only on the count, not when it starts to ache.',
        },
      ],
    },
    {
      id: 'gait',
      title: 'Gait and locomotion',
      purpose: 'Baseline walking, loaded walking and speed changes.',
      steps: [
        { text: 'Walk 10 m on the taped line with a natural arm swing.', cue: 'Both feet finish on the mark.', restart: 'Stepping off the line.' },
        { text: 'Walk 10 m with 5 kg in the right hand.', cue: 'The opposite shoulder does not hike.', exercises: ['d18.throwing-striking'] },
        { text: 'Walk 10 m with 5 kg in each hand.', cue: 'Both loads are set down on a count, not dropped.' },
        { text: 'Walk backward 5 m.', cue: 'Stops without looking down at the feet.', restart: 'Drifting off the line.' },
        { text: 'Side-step left eight steps in stance.', cue: 'Hips stay low and the feet do not cross.' },
        { text: 'Side-step right eight steps.', cue: 'Same rule as the left.' },
        { text: 'Turn 180 degrees on the left foot, plant the right, freeze two seconds.' },
        { text: 'Turn 180 degrees on the right foot, plant the left, freeze two seconds.' },
        { text: 'Jog 20 m easy and break to a walk on the mark.', cue: 'No last-step lurch into the walk.' },
        { text: 'Accelerate 10 m from a standing start.', cue: 'Stays inside the lane.' },
        { text: 'Decelerate to a full stop in three steps and hold the third.' },
      ],
    },
    {
      id: 'direction',
      title: 'Change of direction and stance',
      purpose: 'Cutting, pivoting and the athletic stance underneath both.',
      steps: [
        { text: 'Cut 45 degrees off the right foot and take one step in the new line.' },
        { text: 'Cut 45 degrees off the left foot.' },
        { text: 'Plant and pivot 90 degrees.', cue: 'The plant knee tracks over the foot rather than spinning on a straight joint.' },
        { text: 'Shuffle in stance the marked distance.', cue: 'Feet stay apart and the chest stays over the knees.' },
        { text: 'Drop into an athletic stance and hold five seconds.', cue: 'Knees do not collapse in and the heels stay down.' },
        { text: 'Rise from the stance on a count and stand tall.' },
        {
          text: 'Change direction on a whistle and make the first step the intended line.',
          cue: 'The first step commits to the correct line rather than a stutter.',
          exercises: ['d18.dance-gym.learn-movement'],
        },
      ],
    },
    {
      id: 'squat-hinge',
      title: 'Squat, hinge and single leg',
      purpose: 'Lower-body patterns including one deliberately incorrect trial.',
      steps: [
        { text: 'Squat to the specified depth, pause, and stand.', cue: 'No bounce out of the bottom.' },
        { text: 'Hold parallel for the specified count.', cue: 'Heels down, eyes on a mark.' },
        { text: 'Split squat left, then stand.' },
        { text: 'Split squat right, then stand.' },
        { text: 'Step up left onto the 20 cm box and stand tall on it.' },
        { text: 'Step up right onto the box and stand tall.' },
        { text: 'Step down.', cue: 'The heel meets the floor before weight shifts onto that foot.' },
        { text: 'Lunge-walk six steps.', cue: 'Each back knee tracks and each front heel stays down.' },
        { text: 'Reverse lunge left and return to a still stand.' },
        { text: 'Reverse lunge right and return to a still stand.' },
        { text: 'Hip hinge until the hands reach mid-shin, then stand.', cue: 'Spine stays long throughout.' },
        { text: 'Romanian deadlift pattern with a dowel or empty bar.', cue: 'The bar stays on the legs the whole way.' },
        { text: 'Floor-pick 8 kg with that hinge and stand to a carry position.', cue: 'Pauses in the carry position before moving.' },
        {
          text: 'Floor-pick the same load with a rounded back, then stop.',
          cue: 'One repetition only, then the trial ends.',
          contrast: true,
          exercises: ['d17.manual-handling.totes-and-slots.recover-tote-pulled-with-a-round-back'],
        },
      ],
    },
    {
      id: 'reach',
      title: 'Reach and rotation',
      purpose: 'Overhead and cross-body range, and trunk rotation.',
      steps: [
        { text: 'Reach overhead with both arms and hold end range.', cue: 'Ribs do not flare at the top.' },
        { text: 'Reach overhead left only, right arm at the side.' },
        { text: 'Reach overhead right only, left arm at the side.' },
        { text: 'Cross-body reach high left and return to a still stand.' },
        { text: 'Cross-body reach high right and return to a still stand.' },
        { text: 'Standing toe-touch and return with control.', cue: 'No bounce at the bottom.' },
        { text: 'Sit, reach to the toes, then sit back tall before standing.' },
        { text: 'Rotate the thorax left to end range.', cue: 'Hips stay quiet.' },
        { text: 'Rotate the thorax right to end range.' },
        { text: 'Woodchop high to low left.', cue: 'Finishes square to the start line.' },
        { text: 'Woodchop high to low right.', cue: 'Finishes square.' },
      ],
    },
    {
      id: 'upper-trunk',
      title: 'Upper body and trunk',
      purpose: 'Pressing, bracing and anti-rotation.',
      steps: [
        { text: 'Medicine-ball chest pass and catch the return into the same stance.' },
        { text: 'Medicine-ball rotational throw, then reset the feet.' },
        { text: 'Push-up to a straight body.', cue: 'Elbows lock at the top.' },
        { text: 'Push-up plus with scapular protraction at lockout.' },
        { text: 'Forearm plank 20 s.', cue: 'Hips neither pike nor sag.' },
        { text: 'Side plank left.', cue: 'Straight line from ankle to shoulder.' },
        { text: 'Side plank right.' },
        { text: 'Dead-bug: opposite arm and leg reach, then switch.', cue: 'Low back stays down.' },
        { text: 'Bird-dog left and hold.', cue: 'Hips do not rotate.' },
        { text: 'Bird-dog right and hold.' },
        { text: 'Band pull-apart until the band reaches the chest line, then ease back.' },
        { text: 'Band row until the elbows pass the midline.', cue: 'Ribs stay down.' },
        { text: 'Shoulder internal and external rotation at 90 degrees abducted.' },
      ],
    },
    {
      id: 'transitions',
      title: 'Transitions and floor',
      purpose: 'Getting up and down, which is where most real work starts and ends.',
      steps: [
        { text: 'Kneel to stand without using the hands.' },
        { text: 'Stand to kneel: one knee down, then the other, controlled.' },
        { text: 'Sit to stand from a 45 cm bench, no hands, still finish.' },
        { text: 'Sit to stand from a 30 cm box, no hands, still finish.' },
        { text: 'Floor to stand through a lunge.', restart: 'Using a bear-crawl unless that trial is labelled.' },
        { text: 'Crawl forward 6 m with the specified knee rule and stop on the mark.' },
        { text: 'Crawl backward 4 m.', cue: 'Hips stay level.' },
        { text: 'Bear-crawl the marked length.', cue: 'Knees do not touch.' },
        { text: 'Lateral crawl the marked length.', cue: 'Feet do not cross.' },
      ],
    },
    {
      id: 'jump-balance',
      title: 'Jump, land and balance',
      purpose: 'Impact absorption and single-leg control.',
      steps: [
        { text: 'Jump in place and land quiet, both feet at once.' },
        { text: 'Broad jump, stick the landing, hold two seconds.' },
        { text: 'Step off a 20 cm box and land.', cue: 'Knees track and the landing is quiet.' },
        { text: 'Single-leg balance left 10 s, eyes on a mark.', restart: 'The other foot touching down.' },
        { text: 'Single-leg balance right 10 s.', restart: 'The other foot touching down.' },
        { text: 'Y-balance anterior reach on the specified stance leg.', cue: 'Returns without hopping.' },
        { text: 'Bilateral calf raise to end range, pause, lower.' },
        { text: 'Single-leg calf raise to end range, pause, lower.' },
        { text: 'Knee-to-wall left until the knee touches.', restart: 'The heel lifting; move the foot and retry.' },
        { text: 'Knee-to-wall right.', restart: 'The heel lifting.' },
        { text: 'Jump-rope twenty cycles and stop with both feet quiet.' },
      ],
    },
    {
      id: 'carries',
      title: 'Loaded carries and drags',
      purpose:
        'The scarcest material in this session. Asymmetric loaded gait is common in real work and thin in public motion datasets.',
      steps: [
        { text: 'Farmer carry 15 m and set both loads down on a count.', exercises: ['d17.manual-handling.carrying'] },
        { text: 'Suitcase carry left 15 m.', cue: 'No lean into the empty side.' },
        { text: 'Suitcase carry right 15 m.', cue: 'No lean.' },
        { text: 'Front-rack carry the specified load and distance.', cue: 'Elbows stay up.' },
        { text: 'Overhead carry a light implement, then lower on a count.', cue: 'Ribs down and arms locked.' },
        { text: 'Sled push 10 m with a constant lean.', restart: 'A sprint finish unless that is the trial.' },
        { text: 'Sled drag 10 m.', cue: 'The strap stays off the backs of the legs.' },
        { text: 'Battle-rope slam ten reps and stop in stance with the ropes still.' },
      ],
    },
    {
      id: 'ladder-hang',
      title: 'Ladder, hang and pull',
      purpose: 'Vertical work that overlaps directly with site and warehouse tasks.',
      steps: [
        {
          text: 'Climb eight rungs, one at a time, both feet on each rung before the next hand.',
          exercises: ['d08.access-handling.height.climb-scaffold-hands-on-rungs'],
        },
        { text: 'Descend eight rungs with the same control.', restart: 'Skipping a rung.' },
        { text: 'Hang from a bar 10 s and drop onto the mid-foot.', cue: 'Not onto locked heels.' },
        { text: 'Pull to the chest on a bar or rings and lower to a still hang or stand.' },
      ],
    },
    {
      id: 'react',
      title: 'Throw, catch, kick and react',
      purpose: 'Ballistic chains and externally cued response.',
      steps: [
        { text: 'Throw a ball from standing and finish in balance before looking at the throw.' },
        { text: 'Catch a ball and absorb it.', cue: 'You could throw again without resetting the feet twice.' },
        { text: 'Kick a ball off a planted foot and recover to stance on that plant.' },
      ],
    },
    {
      id: 'falls',
      title: 'Falls and get-ups',
      purpose: 'Controlled loss of position and recovery from the floor.',
      steps: [
        { text: 'Fall to a knee on purpose and recover to stand.', restart: 'Using a hand unless the trial allows it.' },
        { text: 'Get up from side-lying through the specified sequence and finish still.' },
        { text: 'Roll from supine to prone and stop square to the line.' },
      ],
    },
    {
      id: 'closeout',
      title: 'Cool-down and suit off',
      purpose: 'End the session with a drift measurement while the suit is still on the landmarks.',
      steps: [
        { text: 'Cool-down walk the marked distance and end on the mark.' },
        {
          text: 'Post-session T-pose.',
          cue: 'Held until capture confirms the drift measurement is logged.',
          restart: 'Breaking the pose before capture confirms.',
        },
        {
          text: 'Take the suit off in the specified sensor order.',
          cue: 'Nothing is yanked off a landmark.',
        },
      ],
    },
  ],
}

export const PROTOCOLS: Protocol[] = [movementBattery]
